DROP TABLE IF EXISTS orgs_users CASCADE;

CREATE TABLE orgs_users (
  id SERIAL PRIMARY KEY NOT NULL,
  org_id INTEGER REFERENCES orgs(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
