DROP TABLE IF EXISTS logs CASCADE;

CREATE TABLE logs (
  id SERIAL PRIMARY KEY NOT NULL,
  org_id INTEGER REFERENCES orgs(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  pwd_id INTEGER REFERENCES passwords(id) ON DELETE CASCADE,
  type VARCHAR(32),
  time TIMESTAMP
);
